package menutypes

// MenuNodes defines the full menu navigation tree.
var MenuNodes = map[string]MenuNode{
	"menu.root":                      {Label: "主菜单"},
	"menu.tools":                     {Label: "常用工具", Parent: "menu.root"},
	"menu.group.model":               {Label: "模型配置", Parent: "menu.root"},
	"menu.group.system":              {Label: "系统运维", Parent: "menu.root"},
	"menu.group.backend":             {Label: "后端选择", Parent: "menu.group.system"},
	"menu.backend.switch":            {Label: "切换后端", Parent: "menu.group.backend"},
	"menu.auto_retry":                {Label: "自动重试", Parent: "menu.group.backend"},
	"menu.thread":                    {Label: "线程管理", Parent: "menu.root"},
	"menu.workspace":                 {Label: "工作区管理", Parent: "menu.root"},
	"menu.review":                    {Label: "代码审查", Parent: "menu.tools"},
	"menu.quiet":                     {Label: "静默模式", Parent: "menu.tools"},
	"menu.usage":                     {Label: "Token 消耗", Parent: "menu.tools"},
	"menu.history":                   {Label: "历史记录", Parent: "menu.tools"},
	"menu.skills":                    {Label: "技能列表", Parent: "menu.tools"},
	"history.detail":                 {Label: "Turn 详情", Parent: "menu.history"},
	"workspace.new":                  {Label: "新建工作区", Parent: "menu.workspace"},
	"workspace.clone":                {Label: "从仓库创建", Parent: "menu.workspace"},
	"workspace.sandbox.menu":         {Label: "默认沙箱", Parent: "menu.workspace"},
	"workspace.policy.menu":          {Label: "默认策略", Parent: "menu.workspace"},
	"workspace.permission_mode.menu": {Label: "默认权限", Parent: "menu.workspace"},
	"workspace.delete.menu":          {Label: "删除工作区", Parent: "menu.workspace"},
	"workspace.delete.confirm":       {Label: "确认删除", Parent: "workspace.delete.menu"},
	"thread.sandbox.menu":            {Label: "线程沙箱", Parent: "menu.thread"},
	"thread.policy.menu":             {Label: "审批策略", Parent: "menu.thread"},
	"thread.permission_mode.menu":    {Label: "会话权限", Parent: "menu.thread"},
	"menu.model":                     {Label: "模型配置", Parent: "menu.group.model"},
	"menu.fast":                      {Label: "响应速度", Parent: "menu.group.model"},
	"menu.status":                    {Label: "状态面板", Parent: "menu.group.system"},
	"menu.debug.logs":                {Label: "查看日志", Parent: "menu.group.system"},
	"menu.codex_upgrade":             {Label: "Codex 管理", Parent: "menu.group.backend"},
	"menu.claude_upgrade":            {Label: "Claude 管理", Parent: "menu.group.backend"},
	"menu.upgrade":                   {Label: "升级服务", Parent: "menu.group.system"},
	"menu.help":                      {Label: "命令帮助", Parent: "menu.group.system"},
}

// MenuGroupSpecs lists all menu groups.
var MenuGroupSpecs = []MenuGroupSpec{
	{Action: "menu.tools", Label: "常用工具", Description: "常用会话与线程工具入口。", ShowInRoot: true},
	{Action: "menu.group.model", Label: "模型配置", Description: "模型选择与响应速度配置。", ShowInRoot: true},
	{Action: "menu.thread", Label: "线程管理", Description: "查看当前线程状态，并通过下拉切换线程。", ShowInRoot: true},
	{Action: "menu.workspace", Label: "工作区管理", Description: "查看当前工作区状态，并通过下拉切换工作区。", ShowInRoot: true},
	{Action: "menu.group.system", Label: "系统运维", Description: "系统运维与帮助入口。", ShowInRoot: true},
	{Action: "menu.group.backend", Label: "后端选择", Description: "后端切换与各 CLI 管理入口。", ShowInRoot: false},
}

// MenuItemSpecs lists all menu leaf items.
var MenuItemSpecs = []MenuItemSpec{
	{GroupAction: "menu.tools", Action: "menu.interrupt", Label: "中断任务", Slash: "/stop", Kind: MenuItemDirect, IncludeParentAction: true},
	{GroupAction: "menu.tools", Action: "menu.review", Label: "代码审查", Slash: "/review", Kind: MenuItemSubmenu},
	{GroupAction: "menu.tools", Action: "menu.quiet", Label: "静默模式", Slash: "/quiet config", Kind: MenuItemSubmenu},
	{GroupAction: "menu.tools", Action: "menu.compact", Label: "压缩上下文", Slash: "/compact", Kind: MenuItemDirect, IncludeParentAction: true},
	{GroupAction: "menu.tools", Action: "menu.download", Label: "下载文件", Slash: "/download", Kind: MenuItemDirect, IncludeParentAction: true},
	{GroupAction: "menu.tools", Action: "menu.history", Label: "历史记录", Slash: "/history", Kind: MenuItemSubmenu},
	{GroupAction: "menu.tools", Action: "menu.skills", Label: "技能列表", Slash: "/skills", Kind: MenuItemSubmenu},
	{GroupAction: "menu.tools", Action: "menu.usage", Label: "Token 消耗", Slash: "/usage", Kind: MenuItemSubmenu},
	{GroupAction: "menu.tools", Action: "menu.root", Label: "返回上一级", Kind: MenuItemBack},
	{GroupAction: "menu.group.model", Action: "menu.model", Label: "模型配置", Slash: "/model", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.model", Action: "menu.fast", Label: "响应速度", Slash: "/fast config", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.model", Action: "menu.root", Label: "返回上一级", Kind: MenuItemBack},
	{GroupAction: "menu.group.system", Action: "menu.debug", Label: "日志级别", Slash: "/debug", Kind: MenuItemDirect},
	{GroupAction: "menu.group.system", Action: "menu.debug.logs", Label: "查看日志", Slash: "/debug logs", Kind: MenuItemDirect},
	{GroupAction: "menu.group.system", Action: "menu.group.backend", Label: "后端选择", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.system", Action: "menu.upgrade", Label: "升级服务", Slash: "/upgrade", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.system", Action: "menu.status", Label: "状态面板", Slash: "/status", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.system", Action: "menu.help", Label: "命令帮助", Slash: "/help", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.system", Action: "menu.root", Label: "返回上一级", Kind: MenuItemBack},
	{GroupAction: "menu.group.backend", Action: "menu.backend.switch", Label: "切换后端", Slash: "/backend", Kind: MenuItemDirect},
	{GroupAction: "menu.group.backend", Action: "menu.auto_retry", Label: "自动重试", Slash: "/backend retry", Kind: MenuItemDirect},
	{GroupAction: "menu.group.backend", Action: "menu.codex_upgrade", Label: "Codex 管理", Slash: "/codex", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.backend", Action: "menu.claude_upgrade", Label: "Claude 管理", Slash: "/claude", Kind: MenuItemSubmenu},
	{GroupAction: "menu.group.backend", Action: "menu.group.system", Label: "返回上一级", Kind: MenuItemBack},
}
